- lib/intf.js
There is no issue for this. I just found this place to refactoring while reading source code
> Remove duplicated constants

- test/tests.js
Progress on #171 
Minor pull request with sample test code commenting.
- Several comments added to test/tests.js
> First PR: Commenting test code

- lib/dom.js
- lib/events.js
- lib/intf.js
> Get current selection bounds on key navigation.

- lib/contextMenu.js
- Dispatch a togglecolumn event when column visibility is changed in the context menu.
> Add togglecolumn event.

- README.md
Adds fenced code blocks and specifies syntax for each. This enables syntax highlighting of the code in the readme on Github and some markdown editors, etc...
> Fenced code blocks & syntax highlighting for README

- lib/events.js
Fixes issue #199 
- I am adding enough space for a row snap.
> Add an row placeholder on snapToRow.

- lib/draw.js
Fixes issue #153
- Optimizing wrapText function performance by dichotomy
> optimize wrapText function performance

- .github/workflows/release.yml
- .github/workflows/test.yml
- .gitignore
- package-lock.json
Should resolve #175.
- Add `test.yml` workflow file for testing on each push / pull request to `master`
- Add `release.yml` to build into `dist/`, create a GitHub release and publish to NPM / docs
- Start ignoring `dist/` folder (i.e. no longer commit the build)
- Start committing `package-lock.json`
> Add workflows for testing / releasing

- README.md
- Windows WSL testing documentation
> added tips for running tests in Windows under WSL

- lib/defaults.js
- lib/docs.js
- lib/draw.js
to enable hover effect on whole row (instead of single cell)
Fixes issue #.
- 
- 
-
> Add 'hoverMode' attribute 

- lib/events.js
now copy and paste is more like excel
> update copy and paste.

- lib/events.js
Selection should fill down on pasting a single text / cell value.
Bring back if-statement checking for single values and update.
Fixes issue #372
> Fix filling down on filling down single values on paste.

- lib/draw.js
> fix sort icon

- lib/events/index.js
- test/attributes.js
> fix Highlighting incorrect column after repositioning column

- lib/publicMethods.js
fix: string sort when value is null/undefined
> fix string sort when value is null/undefined

- lib/draw.js
- lib/events/index.js
- lib/publicMethods.js
- test/attributes.js
Fixes issue #.
- fix Move multiple columns or Rows
- 
-
> Fix moving multiple columns or rows (#393, #390)

- lib/button.js
- lib/events/index.js
Fixes issue #.
- upgrade to activate dropdown
- fix button is not exposed
> Button in cell

- lib/events/index.js
- lib/intf.js
Apologies for this. Previous PR needed a fix: https://github.com/TonyGermaneri/canvas-datagrid/pull/451#issuecomment-995231820
> Set minimum width when resizing columns and light refactor

- lib/events/index.js
- lib/events/util.js
Fix cut event handling to prevent default and ensure proper placement of cut data on clipboard.
Clean up util module (consistent function definitions).
> Prevent default cut event handling and cleanup

- lib/events/index.js
Fixes issue #462
(But there are still issue #463)
> Fix `scrollCache.x`

- lib/contextMenu.js
- test/index.js
- test/reorder-columns.js
Fixes issue #469 
And add test case for it.
> Fix the behavior of the conext menu item used to hide column

- test/reorder-columns.js
Fixes issue #469 and failed action <https://github.com/TonyGermaneri/canvas-datagrid/actions/runs/1713061848>
> Fix test `reorder-column.js`

- lib/publicMethods.js
> update column resizing including header

- lib/dom.js
Fixes issue #408.
Here is a link to test: https://90zfd.csb.app/408.html
> fix Expanding contents in a cell when editing

- lib/component.js
- lib/contextMenu.js
- lib/events/index.js
- lib/intf.js
As the title said. I find some confusing code when I review the code
> Fix some small bugs and remove some useless code.

- lib/selections/index.js
- test/key-navigation.js
- test/selections.js
Add more integration tests for the PR #498 
These tests can be also treated as an incomplete spec of the new property `selectionList`.
> Add more tests for properties `selections` and `selectionList`

- lib/publicMethods.js
Fixes #261.
- check the value of the `allowSorting` attribute before sorting.
> fix sorting on header click

- lib/selections/index.js
- test/editing.js
> Fix clearing of selected cells when a filter has been applied
