TonyGermaneri/canvas-datagrid

lib/intf.js

Setters for frozenRow and frozenColumn properties should throw an error if the number of visible rows is less than the frozen row's index value.

Fix setters for frozenRow and frozenColumn

---

lib/intf.js

Bad syntax in a doc property caused the doc site to hang.

fixed bad doc syntax

---

lib/events.js
lib/intf.js

Fixes issue #202 
- Remove the check against the scrollHeight that resets the scrollTop to 0.

Remove scrollTop = 0 from setters.

---

lib/events.js

When a grid has extra gray space at the bottom, a user could click in that region then attempt to keyboard navigate.  This caused the rowIndex to be NaN which was throwing an error.

Check for NaN on keypress navigation.

---

lib/events.js

Fixes issue #.
- Add cell to endfreezemove event. Allows for current column to be used to replicate recent changes to grid freeze bar.

Added cell to endfreezemove event.

---

lib/intf.js
lib/publicMethods.js
test/tests.js

Fixes issue #215.
- when data is set via the data setter, this applies the currently set filters to the new data set.
- setFilter keeps current filter even when changing the filter value to a non-existent column
- setFilter applies the proper type filter to a column when the schema filter function is not set

SetDataFilterApply

---

lib/intf.js
lib/publicMethods.js
test/tests.js

Fixes issue #217.
- added tests around current order behavior
- fixes order when sortFunction defaults to string sorter
- fixes order to use sorter on schema if defined
- resorts after setting data
- resorts after filtering data

retain sort state after changing data

---

lib/docs.js
lib/events.js

Fixes issue #216.
- add event *copyonschema* to set column schema for copying
custom the column.name to be copied:
```
grid.addEventListener('copyonschema', function(evt){
evt.column.name = 'Column Name';
});
```
or null the column.name to let column.title be copied:
```
grid.addEventListener('copyonschema', function(evt){
evt.column.name = null;
});
```

dispatch event copyonschema to set column schema for copying

---

lib/component.js

If some style element added a text node. It will cause canvas-datagrid use interHTML to overwrite it's data.
Fixes issue #.
- 
- 
-

Fix a bug: grid.data accidentally set to innerHTML

---

lib/dom.js
lib/main.js

Fixes issue #251 .
https://developer.mozilla.org/en-US/docs/Web/API/Element/createShadowRoot
createShadowRoot is deprecated in Chrome 80. Hence removing the usages.

#251 Remove deprecated createShadowRoot

---

lib/publicMethods.js

Copy/Paste doesn't work if just providing data and no schema. If the schema is auto generated, each column is missing columnIndex which is referenced when pasting content.
Fixes issue #269
- Adding columnIndex to auto generated schema column

Fixing columnIndex key missing from schema column

---

lib/defaults.js
lib/docs.js
lib/events.js

Fixes issue #273.
Add a "singleSelectionMode" option which causes the control/meta keys to be ignored.
This obviously conflicts with "persistantSelectionMode", currently singleSelectionMode overrides persistantSelectionMode.

Add singleSelectionMode setting

---

lib/publicMethods.js

Fixes issue #110.
Removal of repeated function description in `publicMethods.js` to prevent duplication of isCellVisible() method documentation.

isCellVisible documentation issue

---

lib/draw.js

Flickering cells when use HTML rendering (schema data type is 'html' or set cell's innerHTML attribute in 'afterrendercell' event handler)
set grid `autoResizeColumns = true` (because value of cell width is float. Cell also flickering when set float value of column width `grid.setColumnWidth(i, 10.1)` )
see example (from 'Draw HTML via data type’ doc tutorials): https://jsfiddle.net/BlackTea1105/9kmu62jL/1/
the drawHtml function in the libs/draw.js, if cell’s size (width / height) not equals cell cache size (htmlImageCache), will clear cache and regenerate Image Element.
But the HTMLImageElement size (width and height) type always is integer, so if cell’s width is float, its never equals its cache’s width.
So I add more information into htmlImageCache (cell’s size).

resolve flickering cells

---

lib/publicMethods.js

When using a custom formatter method, if the length of the string returned by the custom formatter method is longer than the original string length, the displayed text will be truncated.
This modification solves the problem of text being truncated by using the return value of the formatter method to calculate the width of the string.

column width calculation error when using custom "formatter"

---

lib/docs.js
lib/events.js
lib/intf.js
test/tests.js

Adds `beforepaste` and `afterpaste` events. Includes a rewrite of the `paste` method, more for clarity and adding comments than anything else, but in the process I fixed a bug where attempting to paste beyond the grid boundaries resulted in an error.

Paste event improvements

---

lib/events.js

Mimics Excel's paste function, where copying a single cell and selecting multiple cells and pasting results in the single value being copied over _all_ selected cells.
This does not cover all cases handled by Excel — I will cover those in future PRs.

Fill paste values in multiple selected cells

---

lib/contextMenu.js
lib/defaults.js
lib/docs.js
lib/intf.js
test/tests.js

Replaces PR #297 as I messed up commit-history in my forked repo branch while making a couple of improvements.
I noticed that blank cell values show up as items in the autocomplete filter dropdown menu, however they are invisible. 
Excel, for example, has a `(Blanks)` menu item which allows you filter on blank column values:
This PR adds a menu item (defaults to`(Blanks)` keeping in line with Excel) to the dropdown to enable filtering on blank column values (if present in the column). Blank column values are `null`, `undefined` and an empty string (i.e. with zero or more spaces)
The value of the menu item can be customised using the attribute `blanksText`.

Render a menu item in autocomplete filter dropdown to be able to filter blank column values

---

lib/events.js

Where scrolling and moving your mouse at the same time actually also scrolled the page for a bit.
Fixes issue #285.
- Fix scrolling behaviour in safari (for trackpad and/or magic mouse)
I'll remove the test file if you are willing to take this pull request, but it's there at the moment because it's super easy to test.

Fixes scrolling behaviour in safari.

---

lib/events.js
test/tests.js

This PR changes the regex checking for supported HTML to also match the format coming back from the Windows clipboard. 
It resolves issue #300.

Fix copy/paste of cells in canvas-datagrid on Windows

---

lib/defaults.js
lib/docs.js
lib/draw.js
test/tests.js

Add an attribute `autoResizeRows` which, if set to `true`, will cause automatic resize of rows that have multiline, text-wrapped cell values in them.
It addresses #134

Add autoResizeRows attribute for optionally resizing rows to fit wrapped text

---

lib/component.js

`component.attributeChangedCallback` is always called after the Grid initialisation. Thus initialisation of the `canvas-datagrid ` webcomponent with a schema fails, as args is only respected during the initialisation phase. The bug can be tested like that 
```js
<canvas-datagrid class="myGridStyle" selectionmode="row" autogenerateschema="false"
schema='[{"name":"title", "title":"The Title"}, {"name":"description", "title":"The Description"}, {"name":"foo", "title":"The Foo"}]'>
[
{"title": "row 1 column 1", "description":"row 1 column 2","foo":"row 1 column 3"},
{"title": "row 1 column 1", "description":"row 1 column 2","foo":"row 1 column 3"}
]
</canvas-datagrid>
```
If schema is not applied the titles are auto generated and all lowercase.

Fix webcomponent data and schema attributes

---

lib/publicMethods.js

getHeaderWidth() concatenates a string instead of summing up the column widths.

Fix getHeaderWidth() return value

---

lib/docs.js
lib/dom.js
lib/events.js

Excel and Google Sheets have a notion of "Enter" and "Edit" modes for manipulating a cell's data:
- "Enter" mode is activated when a user starts typing in the active cell. This typing replaces the cell's previous value, and allow the user to quickly navigate to adjacent cells using the arrow keys. This allows you to enter a series of values very quickly.
- "Edit" mode is when you hit the "Enter" key (confusing, no?) to edit the cell's value. It places the text cursor at the end of the cell's content, and arrow keys do not move away from the active cell, but instead move the text cursor around. This mode is intended for more deliberate editing of existing values.
canvas-datagrid previously didn't make a clear distinction, so there was a bug when you started typing in a cell and then …

Make distinction between "enter" and "edit" modes

---

lib/draw.js
test/tests.js

The middle of lines/strokes on canvas is positioned exactly in between two pixels. This is explained here https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Applying_styles_and_colors#A_lineWidth_example
This leads to blurry and too thick lines. 1 px solid black grid lines are displayed as 2 px lines in medium grey. This is somewhat mitigated when lines overlay each other.
The fix attempts to shift all canvas coordinates by half a pixel via the `canvasOffsetTop` and `canvasOffsetLeft` properties.

Render crisp lines/strokes

---

lib/events.js

PR fixes following issue: When copy/pasting a cell from only 1 row, `affectedCells` will not get passed onto the `afterpaste` event. This is caused by the re-assignment of `self.selections` with an empty `selections` array which is only populated in the situation where we are copying multiple rows of data.

Fix bug that causes current selections to be overwritten when cell on only 1 row is selected

---

lib/draw.js

Trigger a resize of the grid when row height has changed due to wrapping cell contents.

Fix grid not resizing when `autoResizeRows` is enabled

---

lib/component.js

Fixes #322
@ndrsn 
The tests didn't catch it, but the function constructor needs to have the name of the parameter populated.
I'm not sure how it's absence will break user code, but it seems like it would be likely to.

Fix: Missing function constructor parameter

---

karma.conf.js
lib/contextMenu.js
lib/dom.js
lib/draw.js
lib/events.js
lib/intf.js
lib/publicMethods.js
lib/touch.js
package-lock.json
package.json
test/attributes.js
test/context-menu.js
test/data-interface.js
test/editing.js
test/filters.js
test/instantation.js
test/public-interface.js
test/sorters.js
test/web-component.js
webpack.config.js

Provides a (possible) solution for #241, by making a distinction between the data that is currently being rendered (due to filtering/sorting), and the entire set of data available to the grid.
- Adds a (internally and externally accessible) property `viewData`, which refers to the _currently rendered data_.
- Adds `boundData` which refers to `self.originalData`. Not sure if we should keep this, or just provide access to `originalData` directly.
- Changes to `cell` object (as created in `drawCell` and emitted in events), see below.
The `drawCell` function constructs a cell object with a number of properties, such as style, value, but also location data. This PR:
- Keeps `rowIndex` and `columnIndex` unchanged for now, although I think we'd want to deprecate those properties to avoid …

Split original source data from viewed data

---

lib/draw.js

where row value has multiple '-', the cell show only before '-';

Fix missing text where value has multiple '-'

---

lib/events.js

When pasting data into a grid that has active filters: 
- Updates of cells don't happen correctly
- Updated cells disappear from filter results if values no longer pass filter criteria; this leads to a confusing user experience as changed cells "all of a sudden" disappear (e.g. Excel and Google Sheets maintain changed values in the filter results).
Changes proposed in this pull request: 
- The `rowIndex` of changed cells is mapped to the `boundRowIndex` so changes apply to `originalData` correctly.
- Don't refresh the grid after a paste event.
The result after changes applied:

Fix paste in filter mode

---

lib/defaults.js
lib/docs.js
lib/dom.js
lib/events.js
lib/intf.js
test/attributes.js
test/drawing.js
test/editing.js
test/public-interface.js
test/resize.js
test/selections.js

Fix issue where selection of 1 or more cells on top or bottom row of the grid (once the grid has been scrolled down) adds addtional cells to the selection.
Steps to reproduce:
- scroll down in the grid (on a scrollable canvas)
- click a cell on the top row, click in the upper half of the cell
- notice the grid scrolling down 1 or 2 rows and increasing the selected area.
Changes proposed in this pull request: 
I've tracked the issue down to a call of [autoScrollZone](https://github.com/TonyGermaneri/canvas-datagrid/blob/7bb0e553075f5cddfb5e70f7b6f2b9b1de813a32/lib/events.js#L557) in the [mousemove](https://github.com/TonyGermaneri/canvas-datagrid/blob/7bb0e553075f5cddfb5e70f7b6f2b9b1de813a32/lib/events.js#L408) event handler. This method …

Fix autoscroll issue when selecting a cell on top or bottom row

---

lib/events.js
test/key-navigation.js

When using keyboard navigation to select cells the selection only grows when additional rows or columns are added. 
This is not in line with Excel/Google sheets behaviour and provides for a sub-optimal user-experience.
This PR changes the selection logic to allow for selections to be more flexible so that they can shrink if arrow keys are moved back:

Shrink keyboard selections

---

tutorials/js/main.js

The tutorial Fiddles currently do not work.  The path given to canvas-datagrid.js file is no longer valid.

Fix Fiddle resource path

---

lib/events/index.js

cant copy when column name or cell value is number
example data
```
const schema = [{"name": 0, "title":"id", "type": "number"}, {"name": 1, "title":"name", "type": "string"}];
const data = [
[1, 'foo'],
[2, null],
];
```

fix: cant copy when column name or cell value is number

---

lib/publicMethods.js
test/resize.js

Double clicking a column border autoresizes the column width (to fit widest cell) but does not emit a `resizecolumn` event. 
This PR fixes this.

Fire event when resizing column by double clicking

---

lib/docs.js
lib/events/index.js
lib/intf.js
lib/publicMethods.js
test/editing.js
test/key-navigation.js

Natively support clearing selected data pressing Delete/Backspace. Clearing selected data fires a `afterdelete` event containing affected cells (an array of tuples in the shape of `[rowIndex, columnIndex, boundRowIndex, boundColumnIndex]`).
This addresses #412.
See https://ynoqp.csb.app/ for interactive demo.

Add `afterdelete` event and `deleteSelectedData()` public method

---

lib/events/index.js
lib/events/util.js
lib/intf.js
test/editing.js
test/key-navigation.js

The cut event handler currently dispatches a `copy` and `cut` event. The copy is fired by reuse of the `copy` event handler and the data is removed from the grid before the `cut` event is dispatched. This is not in line with the [W3C Clipboard API](https://w3c.github.io/clipboard-apis/#clipboard-event-cut) which reads:
> In an editable context, if the event is not canceled the action will place the currently selected data on the system clipboard and remove the selection from the document. The cut event fires before the selected data is removed. When the cut operation is completed, the selection is collapsed.
This PR refactors the `cut` event handler to:
- Move selected-cell-copy-logic to a utility function so it can be used in both `cut` and `copy` event handler.
- Copy selected data to …

Refactor `cut` and `copy` event handlers

---

lib/events/index.js
lib/intf.js
test/resize.js

This moves Canvas Datagrid column resizing behaviour more in line with Excel and Google Sheets.
For example, Excel's column resize behaviour (on dragging or double-clicking resize handle):
Canvas Datagrid after merging:
Here's a sandbox to try: https://lojcx.csb.app/

Resize selected columns simultaneously

---

lib/dom.js
lib/publicMethods.js

* Fix `self.position` method for multi-level nested grids. Add flag `calculatedTree` to avoid calculating offset of nested grid multiple times
* Fix `scrollIntoView `method. Make this method can display the cells fully instead of some parts being hidden by headers
Demo:
* Bugs: <https://qolwi.csb.app/bugs.html>
* Fixed: <https://qolwi.csb.app/index.html>
Reproducing:
1. Scroll right 10px, and double click any column in the first column to edit.
2. Open the inner grid of row 1, then open the inner grid of row 1 of the inner grid you opened. And try to edit the first cell
Screenshots:

Fix cell editing in the inner grid

---

lib/events/index.js

Fix bug:
``` 
Uncaught TypeError: Cannot set properties of undefined (setting 'dragOffset')
at HTMLBodyElement.self.dragReorder (index.js:979)
```
Reproducing:
https://user-images.githubusercontent.com/4303130/147653450-40c8734f-937c-4be6-a623-1583fbec4077.mp4

Fix setting property `dragOffset` of undefined

---

lib/events/util.js
test/editing.js

Small fix to avoid casting `null` to a string `'null'`.

Fix: null values are cast to strings ('null') on copy

---

.eslintrc

* Related Stack Overflow: <https://stackoverflow.com/questions/56337176/prettier-and-eslint-indents-not-working-together>
* Related ESLint config: <https://eslint.org/docs/rules/indent>
---
This PR can remove incorrect warnings and errors reported by ESLint and make developers more comfortable reading and writing the codes. 🤣

Update ESLint config for incorrect errors.

---

lib/publicMethods.js

@ndrsn Urgent patch for <https://canvas-datagrid.js.org/>
Sorry, I missed description text in two functions I wrote. They causes the tutorials feature of current document site down, because the site generator needs generate HTML by `description.innerHTML = marked(formatDocString(i.description));`.

Fix jsDoc for document site

---

lib/intf.js

Fixes a small bug where data is not cleared properly when gird is filtered. Instead of clearing cells in `viewData` we need to modify `originalData`.

Fix clearing data when grid is filtered

---

lib/events/index.js

Fixes issue #.
- Move-selection gets 'stuck' when cursor exits grid

fix Move-selection gets 'stuck' when cursor exits grid

---

test/index.html

Hi @ndrsn, I have run tests in watch mode(`npm run test:watch`) with this patch under multiple OS (Ubuntu and OSX). And all of the results are passed.
---
I mark these codes as comments because these codes cause the async test to be failed in watch mode.    
I guess these codes are duplicate with `window.__karma__.loaded()`. Then they make the async tests are run twice with the same Mocha instance.
``` javascript
window.onload = () => {
mocha.run();
};
// Error:
// Mocha instance is currently running tests, cannot start a next test run until this one is done
```

Remove unnecessary codes in the context file of Karma

---

tutorials/vueExample.html

Hi! Fantastic library!
Although it's so simple, I still didn't immediately get it setup correctly in my Vue Typescript project. The reason is it wasn't entirely clear if I could use the `canvas-datagrid` element right away, or if I had to change any webpack configuration. I've never worked with web-components before.
Apparently, I just had to import the dependency in `main.ts` (or `.js`), and that's it.
I also needed to google for where to put the configuration for ignoredElements.
To make it even easier to get started with Vue, I thought to add these notes to the Vue demo page.
This is what it looks like:
https://jsfiddle.net/vs9k0nau/

Add vue setup instructions

---

lib/docs.js
lib/intf.js
lib/publicMethods.js
test/unhide-indicator.js

Dispatching events on hiding/unhiding columns is useful te be able to store grid state externally, (e.g. in settings or user profile). 
I've now made it so that an event is dispatched for each individual column being hidden even when a group of columns is being hidden. User can handle all individual events or debounce and, on last event, retrieve grid schema to figure out which columns are hidden or not.
Also moved `unhideColumns` to `publicMethods.js`, this seemed appropriate as all the other hide/unhide methods are located there.
Similar approach could be implemented for hiding / unhiding rows, will do as separate PR if agreed on this approach for columns.

Dispatch column hide/unhide events

---

lib/events/index.js

The PR is used for fixing the bug in the PR #483 
Here is a explaining of it:
1. Setting the size properties (`width`/`height`) to the canvas element can causes the canvas and its state be cleared even if the size is the same.
2. So the grid loss all rendered content if we don't draw again after a function call to `self.resize()`
Even though this PR fixes it. But I still recommend using the code `self.resize(true)` to instead of the following code:
``` javascript
self.draw(true);
self.resize();
// or:
self.resize();
self.draw(true);
```
Because it can reduces unnecessary function calls. (Because `self.draw` may also call the `self.resize` if the `checkScrollHeight` is true. https://github.com/TonyGermaneri/canvas-datagrid/blob/master/lib/draw.js#L2890-L2892)

Fix the bug that the canvas being cleared under unusual refresh flow

---

tutorials/js/main.js

A one line patch for current document site.
The document site can still works well even we don't comment any elements(function, parameter, ...) in the jsDoc.

Fix `formatDocString` for the uncommented elements

---

lib/docs.js

Fixes typos in documentation:
- Change typo `activeHeaderCellBackgroundColor` to the correct name: `activeColumnHeaderCellBackgroundColor`
- Change typo `activeHeaderCellColor` to the correct name: `activeColumnHeaderCellColor`
I was struggling with getting it to work until I noticed that the documentation is wrong on that part.
See defaults file: https://github.com/TonyGermaneri/canvas-datagrid/blob/master/lib/defaults.js

Fix activeColumnHeaderCell docs

---

lib/dom.js

Write className directly to created element so that it could be targeted by CSS.
Issue:
- At the moment, context menu is built manually by DOM manipulation. Suggested to add a class name to each created element to allow further manipulation.
- One example would be adding padding to context menu items, which is not possible at the moment due to missing property.
- This also should engage GPU optimizations for properties stored in CSS, while inline styles from JS will take precedence over the CSS in case of a conflict.
- Extended dom.js to simply overwrite className - right now it is not used anywhere and should be a simple and non-breaking addition.

Add class name to allow targeting context menu by CSS

---

lib/publicMethods.js

Fix `allowColumnReordering: true` not working while `allowRowReordering` is `false`

---

lib/events/index.js

Fixes issue #518.
- When you paste data, the correct column is determined based on `self.orders.columns`

closes #518

---

lib/selections/index.js
test/editing.js

This PR solves an issue when copying data while having rows above the selection that aren't selected. You can see that rows above the selection lead to new lines in the `textString` that is put on the clipboard:
Null values in the sparse array returned by `getSelectedData` are filtered out before data is transformed to text, html, csv or json string.

On copy, only include data from rows that are in the actual selection

---

lib/docs.js

add type docs for: 
• style.columnHeaderCellBackgroundColor
• style.columnHeaderCellBorderColor
• style.columnHeaderCellBorderWidth
• style.height
• style.width
fix wrong doc comments for 
• columnHeaderCellCapBackgroundColor
• columnHeaderCellCapBackgroundColor
• columnHeaderCellCapBorderColor

docs: Update docs.js with missing types
